stages:
- formatting
- testing
- deploy
formatting:
  stage: formatting
  image: julia:latest
  script:
    - |
      julia --eval '
      import Pkg
      Pkg.add("JuliaFormatter")
      using JuliaFormatter
      properly_formatted = format("./src"; verbose = true)
      exit(properly_formatted ? 0 : 1)'
test:latest:
  stage: "testing"
  image: "julia:latest"
  script:
    - |
      julia --project=@. --eval '
      import Pkg; Pkg.test(; coverage = true); Pkg.add("Coverage"); Pkg.instantiate()
      using Coverage
      processed = process_folder()
      covered_lines, total_lines = get_summary(processed)
      percentage = covered_lines / total_lines * 100
      return println("($(percentage)%) covered")'
  coverage: "/\\(\\d+.\\d+\\%\\) covered/"
pages:
  stage: deploy
  image: julia:latest
  script:
    - julia --project=docs -e 'import Pkg; Pkg.develop(;path=".");Pkg.instantiate()' # Initialize environment
    - julia --project=docs docs/make.jl                       # Build documentation
    - mv docs/build public  # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
