name = "EnergyModelsHeat"
uuid = "ad1b8b27-e232-4da9-b498-bea9c19a30d7"
authors = ["Lars Hellemo, Hanne Kauko, and Till Holmes"]
version = "0.1.0"

[deps]
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[compat]
EnergyModelsBase = "0.9.0"
JuMP = "1.23.5"
TimeStruct = "0.9.1"
julia = "1.10"
